In [ ]:
#파이썬에서 데이터 분석 시 pandas 라이브러리를 활용
#pandas - panel Data
#데이터 분석 - 표 형태의 빅데이터에서 곁측치와 이상치를 제거, 데이터를 가공, 정규화하여
#             데이터에서 유의미한 정보 및 지식, 지혜를 얻기 위한 작업

In [ ]:
#최초 한번은 pandas 라이브러리를 설치
#jupyter 셀에서 설치할때는 '!' 붙여야함
#py 파일에서는 pandas 설치 시 '!' 붙이지않음. 
!pip install pandas

Requirement already satisfied: pandas in c:\users\grs\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\grs\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\grs\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\grs\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\grs\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#pandas 라이브러리 사용을 위해 import
#pandas 파일을 불러와서 앞으로 'pd'라는 이름으로 사용하겠다.
import pandas as pd

In [4]:
#pandas 라이브러리를 사용하면 엑셀, csv, json, 딕셔너리 데이터를 표 형태의 데이터로 가공

#딕셔너리 데이터로 dataframe(표형태) 만들기
data = {
  '이름' : ['김자바', '이자바', '박자바', '정캐트', '최캐드'],
  '학급' : ['자바반', '자바반', '자바반', '캐드반',' 캐드반'],
  '국어점수' : [90,80,70,100,90],
  '영어점수' : [70,80,80,70,90],
  '평균' : [80.0, 80.0, 75.0, 85.0, 90],
  '취미' : ['독서' , '', '', '요가', '축구']
}

df = pd.DataFrame(data)
df

    이름    학급  국어점수  영어점수    평균  취미
0  김자바   자바반    90    70  80.0  독서
1  이자바   자바반    80    80  80.0
2  박자바   자바반    70    80  75.0
3  정캐트   캐드반   100    70  85.0  요가
4  최캐드   캐드반    90    90  90.0  축구

In [6]:
# 엑셀 파일 저장을 위해 라이브러리 설치
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#위 df 데이터를 엑셀로 저장하기
#엑셀 파일로 저장하면 df에 있던 index정보까지 엑셀에 저장됨
# df.to_excel('test1.xlsx')

#엑셀 파일 저장 시 index를 제외하고 저장
#참 = True, 거짓 = False
df.to_excel('test2.xlsx', index=False)

In [10]:
# 엑셀 파일 가져오기
new_df = pd.read_excel('test2.xlsx')
new_df

    이름    학급  국어점수  영어점수  평균   취미
0  김자바   자바반    90    70  80   독서
1  이자바   자바반    80    80  80  NaN
2  박자바   자바반    70    80  75  NaN
3  정캐트   캐드반   100    70  85   요가
4  최캐드   캐드반    90    90  90   축구

In [11]:
#csv파일 가져오기
edu_df = pd.read_csv('edu_users.csv')
edu_df

,rate_math,rate_science,rate_english,rate_humanities,rate_art,tot_time,device,gender,age,resub_yn,comb_yn,othersub_yn,leave_yn
0,0.375,0.797,0.828,0.896,0.394,17.09,mobile,M,30,N,N,Y,1
1,0.951,0.482,0.765,0.909,0.473,28.57,tablet,F,25,N,Y,N,1
2,0.732,0.117,0.574,0.314,0.855,40.97,tablet,F,24,N,N,N,0
3,0.599,0.125,0.956,0.691,0.340,8.09,mobile,M,14,Y,N,N,1
4,0.156,0.686,0.200,0.272,0.870,45.34,tablet,F,15,Y,N,N,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,0.626,0.492,0.212,0.897,0.607,16.80,pc,M,24,Y,N,Y,0
1246,0.131,0.577,0.664,0.119,0.167,33.37,tablet,F,40,N,N,N,0
1247,0.033,0.866,0.411,0.328,0.797,27.37,mobile,M,23,N,N,N,0
1248,0.921,0.981,0.402,0.816,0.720,NaN,pc,F,23,Y,N,Y,0
1249,0.617,0.408,0.885,0.597,0.086,17.90,pc,M,15,N,N,N,0